library(usethis)
library(haven)
library(readxl)
library(readr)

therapist <- read_sav("data-raw/therapist self-confidence.sav")
tvability <- read_excel("data-raw/keith tv ability.xls")
ISMI <- read_csv("data-raw/ISMI_data.csv")
alcohol1 <- read.table("https://stats.idre.ucla.edu/stat/r/examples/alda/data/alcohol1_pp.txt", header=T, sep=",")
liar <- read_csv("data-raw/liar.csv")
neuro_data <-read_sav("data-raw/neurodata_Week 10.sav")
birthweight <-read_sav("data-raw/birthweight.sav")
exam_anxiety <-read_csv("data-raw/exam anxiety.csv")
bsri <- read_sav("data-raw/BSRI.sav")
CHD <- read_sav("data-raw/CHD.sav")
diabetes <- read_sav("data-raw/diabetes.sav")
private_practice <-read_sav("data-raw/private practice mediation.sav")
aba_data <- read_sav("data-raw/aba data.sav")
neuro_FIM <- read_sav("data-raw/neurological FIM.sav")
load("data-raw/outliers.RData")

usethis::use_data(aba_data, overwrite = TRUE)
usethis::use_data(alcohol1, overwrite = TRUE)
usethis::use_data(birthweight, overwrite = TRUE)
usethis::use_data(bsri, overwrite = TRUE)
usethis::use_data(CHD, overwrite = TRUE)
usethis::use_data(diabetes, overwrite = TRUE)
usethis::use_data(exam_anxiety, overwrite = TRUE)
usethis::use_data(inflated, overwrite = TRUE)
usethis::use_data(deflated, overwrite = TRUE)
usethis::use_data(ISMI, overwrite = TRUE)
usethis::use_data(liar, overwrite = TRUE)
usethis::use_data(neuro_data, overwrite = TRUE)
usethis::use_data(neuro_FIM, overwrite = TRUE)
usethis::use_data(private_practice, overwrite = TRUE)
usethis::use_data(therapist, overwrite = TRUE)
usethis::use_data(tvability, overwrite = TRUE)


usethis::use_r("tvability")
